Add total value
landingi/bookkeeping-bundle pull request #10
Opened 2021-03-11 14:09 UTC by miroslawgnielka

Added InvoiceTotalValue and some getters .

2021-03-11 14:34 UTC, Ferror requested changes

2021-03-11 14:34 UTC, Ferror commented on src/Bookkeeping/Invoice/InvoiceTotalValue.php
> +    public function __construct(string $totalValue)
Hajs trzymamy w intach i nie ma testów na ten VO

2021-03-12 07:46 UTC, miroslawgnielka commented on src/Bookkeeping/Invoice/InvoiceTotalValue.php
> +    public function __construct(string $totalValue)
zmienione

2021-03-12 10:19 UTC, mateuszpapis approved these changes

2021-03-12 14:00 UTC, Ferror approved these changes

2021-03-12 14:00 UTC, merged