Tax can also be 'NP' when Tax is not applied
landingi/bookkeeping-bundle pull request #11
Opened 2021-03-12 09:53 UTC by miroslawgnielka

2021-03-12 10:14 UTC, mateuszpapis commented on src/Wfirma/Invoice/WfirmaInvoiceItem.php
> +            if (WfirmaValueAddedTax::NO_VAT === $this->vatId) {
jak nie chcesz zmienic tego tax rate na stringa tylko to robić w ten sposób, to może już niech to pójdzie lepiej jako

if (WfirmaValueAddedTax::NO_VAT === $this->vatId) {
}
else if ($this->vatId) 
{
}
else {
}

2021-03-12 14:02 UTC, Ferror requested changes, later dismissed

2021-03-12 14:02 UTC, Ferror commented on src/Wfirma/Invoice/WfirmaInvoiceItem.php
> +            if (WfirmaValueAddedTax::NO_TAX === $this->vatId) {
Zrób na to test.

2021-03-15 07:57 UTC, miroslawgnielka commented on src/Wfirma/Invoice/WfirmaInvoiceItem.php
> +            if (WfirmaValueAddedTax::NO_TAX === $this->vatId) {
dodane

2021-03-15 08:24 UTC, mateuszpapis approved these changes

2021-03-15 08:25 UTC, merged